"""HTML export implementation — self-contained single-file report."""

import html
from pathlib import Path

from tg_harvest.config.constants import DEFAULT_DATE_FORMAT
from tg_harvest.exporters.base import BaseExporter, build_row, filter_fields
from tg_harvest.models.parse_result import ParseResult

MEDIA_ICONS: dict[str, str] = {
    "photo": "\U0001f4f7",
    "video": "\U0001f3ac",
    "document": "\U0001f4c4",
    "audio": "\U0001f3b5",
    "voice": "\U0001f3a4",
    "video_note": "\u23fa",
    "sticker": "\U0001f4a0",
    "gif": "\U0001f3de\ufe0f",
    "poll": "\U0001f4ca",
    "geo": "\U0001f4cd",
    "contact": "\U0001f464",
    "web_page": "\U0001f310",
}


class HtmlExporter(BaseExporter):
    """Export parse results as a self-contained HTML report."""

    async def export(self, result: ParseResult, output_path: Path, file_suffix: str = "") -> Path:
        output_path.mkdir(parents=True, exist_ok=True)

        channel_name = result.channel.username or str(result.channel.id)
        timestamp = result.parsed_at.strftime("%Y%m%d_%H%M%S")
        file_path = output_path / f"{channel_name}_{timestamp}{file_suffix}.html"

        content = self._render(result)
        file_path.write_text(content, encoding="utf-8")
        return file_path

    def _render(self, result: ParseResult) -> str:
        ch = result.channel
        rows = []
        for msg in result.messages:
            row = filter_fields(build_row(msg), self.fields)
            rows.append(row)

        headers = self.fields
        total = len(rows)

        # Calculate summary stats
        views_list = [r.get("views") for r in rows if r.get("views") is not None]
        avg_views = sum(views_list) / len(views_list) if views_list else 0

        table_headers = "".join(f"<th>{html.escape(h)}</th>" for h in headers)
        table_rows = self._build_table_rows(rows, headers)

        return f"""<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(ch.title)} — TG Harvest Report</title>
{self._css()}
</head>
<body>
<div class="container">

<header class="channel-header">
  <div class="channel-info">
    <h1>{html.escape(ch.title)}</h1>
    <p class="channel-meta">
      {("@" + html.escape(ch.username)) if ch.username else "Private channel"}
      &middot; ID: {ch.id}
      {f"&middot; {ch.members_count:,} members" if ch.members_count else ""}
    </p>
    <p class="parse-meta">
      Parsed at {result.parsed_at.strftime(DEFAULT_DATE_FORMAT)} UTC
      &middot; {total:,} messages
    </p>
  </div>
  <button class="theme-toggle" onclick="toggleTheme()" title="Toggle theme">
    \U0001f319
  </button>
</header>

<div class="stats-bar">
  <div class="stat">
    <span class="stat-value">{total:,}</span>
    <span class="stat-label">Messages</span>
  </div>
  <div class="stat">
    <span class="stat-value">{avg_views:,.0f}</span>
    <span class="stat-label">Avg Views</span>
  </div>
  <div class="stat">
    <span class="stat-value">{ch.members_count or 0:,}</span>
    <span class="stat-label">Members</span>
  </div>
</div>

<div class="toolbar">
  <input type="text" id="filterInput" placeholder="Filter messages..."
         onkeyup="filterTable()">
  <span class="row-count" id="rowCount">{total} rows</span>
</div>

<div class="table-wrap">
<table id="dataTable">
<thead>
<tr>{table_headers}</tr>
</thead>
<tbody>
{table_rows}
</tbody>
</table>
</div>

<footer>
  Generated by <strong>TG Harvest</strong>
</footer>

</div>
{self._js()}
</body>
</html>"""

    def _build_table_rows(self, rows: list[dict], headers: list[str]) -> str:
        lines = []
        for row in rows:
            cells = []
            for h in headers:
                val = row.get(h, "")
                cell = self._format_cell(h, val)
                cells.append(f"<td>{cell}</td>")
            lines.append("<tr>" + "".join(cells) + "</tr>")
        return "\n".join(lines)

    def _format_cell(self, field: str, value: object) -> str:
        if value is None or value == "":
            return ""

        str_val = str(value)

        if field == "url" and str_val.startswith("https://"):
            return f'<a href="{html.escape(str_val)}" target="_blank">link</a>'

        if field == "media_type" and str_val:
            icon = MEDIA_ICONS.get(str_val, "")
            return f"{icon} {html.escape(str_val)}"

        if field == "reactions_detail" and str_val:
            parts = str_val.split("; ")
            badges = []
            for part in parts:
                badges.append(f'<span class="badge">{html.escape(part)}</span>')
            return " ".join(badges)

        if field == "text":
            escaped = html.escape(str_val)
            if len(escaped) > 300:
                escaped = escaped[:300] + "..."
            return f'<span class="text-cell">{escaped}</span>'

        return html.escape(str_val)

    @staticmethod
    def _css() -> str:
        return """<style>
:root {
  --bg: #ffffff; --bg2: #f5f7fa; --fg: #1a1a2e;
  --border: #e0e0e0; --accent: #0088cc; --accent2: #e3f2fd;
  --header-bg: #0088cc; --header-fg: #ffffff;
  --badge-bg: #e8f5e9; --badge-fg: #2e7d32;
  --shadow: 0 2px 8px rgba(0,0,0,.08);
}
[data-theme="dark"] {
  --bg: #1a1a2e; --bg2: #16213e; --fg: #e0e0e0;
  --border: #333; --accent: #4fc3f7; --accent2: #1a3a5c;
  --header-bg: #0a4f7a; --header-fg: #e0e0e0;
  --badge-bg: #1b3d20; --badge-fg: #81c784;
  --shadow: 0 2px 8px rgba(0,0,0,.3);
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
       background: var(--bg); color: var(--fg); line-height: 1.5; }
.container { max-width: 1400px; margin: 0 auto; padding: 20px; }
.channel-header { display: flex; justify-content: space-between; align-items: flex-start;
                   background: var(--header-bg); color: var(--header-fg);
                   padding: 24px 32px; border-radius: 12px; margin-bottom: 20px; }
.channel-header h1 { font-size: 1.6em; margin-bottom: 4px; }
.channel-meta, .parse-meta { opacity: .85; font-size: .9em; }
.theme-toggle { background: none; border: 2px solid var(--header-fg); color: var(--header-fg);
                 font-size: 1.4em; cursor: pointer; border-radius: 50%;
                 width: 44px; height: 44px; display: flex; align-items: center;
                 justify-content: center; transition: opacity .2s; }
.theme-toggle:hover { opacity: .7; }
.stats-bar { display: flex; gap: 16px; margin-bottom: 20px; }
.stat { flex: 1; background: var(--bg2); border: 1px solid var(--border);
         border-radius: 10px; padding: 16px; text-align: center; }
.stat-value { display: block; font-size: 1.5em; font-weight: 700; color: var(--accent); }
.stat-label { font-size: .85em; opacity: .7; }
.toolbar { display: flex; align-items: center; gap: 12px; margin-bottom: 12px; }
#filterInput { flex: 1; padding: 10px 14px; border: 1px solid var(--border);
                border-radius: 8px; font-size: .95em; background: var(--bg2);
                color: var(--fg); outline: none; }
#filterInput:focus { border-color: var(--accent); }
.row-count { font-size: .85em; opacity: .6; white-space: nowrap; }
.table-wrap { overflow-x: auto; border-radius: 10px; box-shadow: var(--shadow);
               border: 1px solid var(--border); }
table { width: 100%; border-collapse: collapse; font-size: .88em; }
thead th { background: var(--accent2); color: var(--fg); padding: 10px 12px;
            text-align: left; cursor: pointer; user-select: none; white-space: nowrap;
            position: sticky; top: 0; border-bottom: 2px solid var(--border); }
thead th:hover { opacity: .8; }
tbody tr { border-bottom: 1px solid var(--border); transition: background .15s; }
tbody tr:hover { background: var(--accent2); }
td { padding: 8px 12px; vertical-align: top; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
.badge { display: inline-block; background: var(--badge-bg); color: var(--badge-fg);
          padding: 2px 8px; border-radius: 12px; font-size: .8em; margin: 1px 2px; }
.text-cell { max-width: 400px; display: inline-block; word-break: break-word; }
footer { text-align: center; padding: 24px; opacity: .5; font-size: .85em; }
@media (max-width: 768px) {
  .stats-bar { flex-direction: column; }
  .channel-header { flex-direction: column; gap: 12px; }
}
</style>"""

    @staticmethod
    def _js() -> str:
        return """<script>
function toggleTheme(){
  var d=document.documentElement;
  var t=d.getAttribute('data-theme')==='dark'?'light':'dark';
  d.setAttribute('data-theme',t);
  localStorage.setItem('tg-harvest-theme',t);
}
(function(){
  var saved=localStorage.getItem('tg-harvest-theme');
  if(saved)document.documentElement.setAttribute('data-theme',saved);
})();
function filterTable(){
  var input=document.getElementById('filterInput').value.toLowerCase();
  var rows=document.querySelectorAll('#dataTable tbody tr');
  var count=0;
  rows.forEach(function(row){
    var text=row.textContent.toLowerCase();
    var show=text.indexOf(input)>-1;
    row.style.display=show?'':'none';
    if(show)count++;
  });
  document.getElementById('rowCount').textContent=count+' rows';
}
document.querySelectorAll('#dataTable thead th').forEach(function(th,idx){
  th.addEventListener('click',function(){
    var table=document.getElementById('dataTable');
    var tbody=table.querySelector('tbody');
    var rows=Array.from(tbody.querySelectorAll('tr'));
    var asc=th.dataset.sort!=='asc';
    th.dataset.sort=asc?'asc':'desc';
    rows.sort(function(a,b){
      var av=a.children[idx].textContent.trim();
      var bv=b.children[idx].textContent.trim();
      var an=parseFloat(av),bn=parseFloat(bv);
      if(!isNaN(an)&&!isNaN(bn))return asc?an-bn:bn-an;
      return asc?av.localeCompare(bv):bv.localeCompare(av);
    });
    rows.forEach(function(r){tbody.appendChild(r);});
  });
});
</script>"""
